sudo: required
services:
  - docker

script:
  - docker build -t johnsonfreemanclarke/node .
  - docker images johnsonfreemanclarke/node

deploy: 
  provider: script
  script: docker push johnsonfreemanclarke/node
  on:
    branch: master
